services:
  postgres:
    image: postgres
    container_name: devnology-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devnology
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devnology-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/devnology
    depends_on:
      - postgres

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devnology-web
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
